BEGIN;
INSERT INTO todos (title, description) VALUES
('Learn SQL', 'Understand the basics of SQL'),
('Learn PostgreSQL', 'Dive into PostgreSQL features'),
('Database Normalization', 'Study database normalization techniques'),
('Build CRUD App', 'Create a basic CRUD application with SQL'),
('Indexing in SQL', 'Learn about SQL indexing for optimization'),
('Joins in SQL', 'Practice SQL joins and their types'),
('Stored Procedures', 'Create stored procedures in PostgreSQL'),
('Views in SQL', 'Understand and create views in SQL'),
('Triggers in SQL', 'Create triggers for automated tasks'),
('SQL Aggregation', 'Practice SQL aggregation functions'),
('Database Transactions', 'Learn about transactions and ACID properties'),
('User Authentication', 'Implement user authentication in SQL'),
('Data Backup', 'Practice SQL data backup and restoration'),
('SQL Constraints', 'Learn about SQL constraints'),
('Optimize Queries', 'Optimize SQL queries for better performance'),
('Advanced Joins', 'Practice complex join statements'),
('Partitioning', 'Learn partitioning strategies in SQL'),
('Window Functions', 'Practice SQL window functions'),
('Full Text Search', 'Implement full-text search in PostgreSQL'),
('Database Migration', 'Understand database migration processes'),
('API Integration', 'Integrate SQL with APIs'),
('Learn ER Diagrams', 'Understand and create ER diagrams'),
('Database Security', 'Implement security best practices'),
('Data Encryption', 'Apply encryption techniques for sensitive data'),
('Backup Strategies', 'Learn about effective backup strategies'),
('SQL Injection', 'Learn how to prevent SQL injection attacks'),
('Audit Logs', 'Set up audit logs for database activities'),
('Query Plans', 'Understand and analyze query plans'),
('Replication', 'Implement database replication'),
('Data Warehousing', 'Learn about data warehousing concepts'),
('JSON Data', 'Store and manipulate JSON data in SQL'),
('Recursive Queries', 'Practice writing recursive queries'),
('Database Caching', 'Implement caching strategies for databases'),
('Real-time Analytics', 'Set up real-time analytics with SQL'),
('Learn PL/pgSQL', 'Practice procedural language in PostgreSQL'),
('Temporal Data', 'Work with temporal data in SQL'),
('User Roles', 'Implement user roles and permissions'),
('Data Validation', 'Implement data validation rules in SQL'),
('Materialized Views', 'Learn about materialized views in SQL'),
('Data Compression', 'Apply data compression techniques'),
('Data Archiving', 'Implement data archiving for older records'),
('Cross-database Queries', 'Execute cross-database queries'),
('SQL Standards', 'Study SQL standards and compatibility'),
('Data Masking', 'Implement data masking techniques'),
('Graph Data', 'Work with graph data in SQL'),
('Learn XML in SQL', 'Store and query XML data'),
('Spatial Data', 'Work with spatial data types'),
('Data Recovery', 'Practice data recovery strategies'),
('Database Refactoring', 'Refactor database for better performance');
COMMIT;
