version: "3.9"

# Common configurations for reuse
x-common: &common-settings
  tty: true
  stdin_open: true
  env_file: .env

services:
  todo-postgres:
    <<: *common-settings
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        POSTGRES_IMAGE: $POSTGRES_IMAGE
    container_name: todo-pg
    volumes:
      - $POSTGRES_VOLUME1
    ports:
      - $POSTGRES_CONTAINER_PORT:$POSTGRES_PORT

  todo-mongo:
    <<: *common-settings
    image: $MONGODB_IMAGE
    container_name: todo-mongo
    volumes:
      - $MONGODB_VOLUME1
      - $MONGODB_VOLUME2
    ports:
      - $MONGODB_CONTAINER_PORT:$MONGODB_PORT
